// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountKind } from "./AccountKind";

/**
 * The only shape ever read back for an account — always carries its
 * derived balance. There is deliberately no `Account` without a balance:
 * reading an account without its balance was how `buckets.current_balance`
 * went stale in the old schema.
 */
export type AccountBalance = { id: number, name: string, kind: AccountKind, target_amount: number | null, credit_limit: number | null, liquid: boolean, archived: boolean, 
/**
 * Signed; negative on a credit account means debt.
 */
balance: number, };
