// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the CLI and GUI show after a backup.
 */
export type BackupInfo = { path: string, 
/**
 * Local time, RFC 3339.
 */
created_at: string, revision: number, schema_version: number, entries: number, automatic: boolean, };
