// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `period` is stored as canonical "YYYY-MM" text, matching `entries` date
 * ranges rather than the old denormalized month/year integer pair.
 */
export type Budget = { id: number | null, concept: string, monthly_limit: number, period: string, };
