// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryKind } from "./EntryKind";

export type Entry = { id: number, date: string, kind: EntryKind, amount: number, from_account_id: number | null, to_account_id: number | null, from_account: string | null, to_account: string | null, concept: string | null, subconcept: string | null, description: string | null, };
