// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of the `ledger_status()` RPC.
 */
export type LedgerStatus = { 
/**
 * Global revision: goes up on every insert, update and delete.
 */
revision: number, schema_version: number, };
