// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BudgetVsActual } from "./BudgetVsActual";
import type { ConceptSummary } from "./ConceptSummary";
import type { Period } from "./Period";

/**
 * A month's activity. `total_expense` (accrued) is what budgets compare
 * against; `cash_out` is what actually left spending accounts that month.
 * The two differ exactly when a card was charged (accrued but no cash
 * left), a card was paid (cash left, nothing was newly consumed), or an
 * expense was funded straight from savings (accrued but no cash left).
 */
export type MonthlyReport = { period: Period, total_income: number, total_expense: number, cash_out: number, net_flow: number, by_concept: Array<ConceptSummary>, budgets: Array<BudgetVsActual>, 
/**
 * Expense funded from an emergency/target account. Detail-only.
 */
from_savings: number, 
/**
 * Expense charged to a credit account. Detail-only.
 */
on_credit: number, 
/**
 * Transfers spending -> emergency/target this month (deposits).
 */
savings_contributions: number, 
/**
 * Transfers emergency/target -> spending this month (withdrawals to
 * cash — NOT expenses; see the bucket-withdraw vs. direct-spend note).
 */
savings_withdrawals: number, 
/**
 * Transfers spending -> credit this month (paying down the card).
 */
card_payments: number, };
