// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountBalance } from "./AccountBalance";

/**
 * Point-in-time balances across all (non-archived) accounts.
 */
export type NetWorth = { accounts: Array<AccountBalance>, 
/**
 * Sum of `spending` account balances — the real, carry-forward "flujo".
 */
cash_on_hand: number, 
/**
 * Sum of `emergency` + `target` account balances.
 */
savings: number, 
/**
 * Sum of credit account debt, reported as a positive number.
 */
credit_debt: number, net: number, };
