// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A calendar month, e.g. "2026-07". Backs all period-scoped queries via
 * half-open date ranges (`start()` .. `end_exclusive()`), never `strftime`
 * in a `WHERE` clause, so range queries can use an index on `entries.date`.
 */
export type Period = string;
