// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an income into `to` would auto-split into the emergency fund.
 */
export type SplitPreview = { pct: number, amount: number, fund: string, };
